<style>
	table tr td{font-size:12px;}
	table tr th{font-size:13px;}
	div{} 
	.signature{
		border-bottom-style:solid;
		font-size:14pt;
		page-break-after:always;

		text-align: center;
		height: 20px;
		width: 100%;
		margin:0px auto;
		position:fixed;
		bottom:0px;
	}
</style>
<div class="messages">
	<?php
		if($this->session->flashdata('message_arr')) {
			$message_arr = $this->session->flashdata('message_arr') ;
			
			foreach($message_arr as $key=>$value){
				echo '<span style="color:red;">'.$value.'</span>';
			}
		}  
	?> 
	 
</div>
<script type="text/javascript">   
	function PrintDivOnly() {   
		var divToPrint = document.getElementById('print_div'); 
		var popupWin = window.open('', '_blank');
		popupWin.document.open();
		popupWin.document.write('<html><body onload="window.print()"><div id="print_div">' + divToPrint.innerHTML + '</div></body></html>');
		popupWin.document.close();
	}
</script>
<a title="Go Back to Orders" style="float: right;" href="<?php echo base_url(); ?>index.php/bluedartshippingprint/">Go Back to Orders</a>

<a title="Export Soft Data" style="float: right;margin-right: 30px;" href="<?php echo base_url(); ?>index.php/bluedartshippingprint/exportsoftdata?batch_id=<?php echo $batch_id ;?>">Export Soft Data</a>

<a title="Email Soft Data" style="float: right;margin-right: 30px;" href="<?php echo base_url(); ?>index.php/bluedartshippingprint/emailexportsoftdata?batch_id=<?php echo $batch_id ;?>">Email Soft Data</a>
 
<input name="b_print" style="float: right;margin-right: 30px;" type="button" class="ipt"  onClick="PrintDivOnly();" style="float:right;" value="Print This Now">
<br/><br/>
<div id="print_div">
	<table width="800" style="border: 1px solid;" cellpadding="5">
		<tr>
			<td style="border-bottom: 1px solid;" align="center"> 
				 
				<p style="font-size:35px">Enovate Lifestyles Private Limited</p>
						 
			</td>
		</tr> 
		<tr>
			<td style="border-bottom: 1px solid;"> 
				<table width="100%" >
					<tr>
						<td align="left">
							<b>Manifest Sheet For :</b><br/>Enovate Lifestyles Private Limited
						</td> 
						<td align="left">
							<b>Date</b> : <?php echo date('d/m/Y',time());?>
						</td>  
						<td align="left">
							<b>Courier</b>: Blue Dart
						</td> 
						<td align="left">
							<b>Batch Number</b> : 
						</td> 
						<td align="left">
							<b>Generated By</b> :  Enovate Lifestyles Private Limited
						</td>
					</tr>
				</table>  
			</td>
		</tr>  
		<tr>
			<td > 
				<table width="100%" style="width:800px">
					<tr>
						<th align="left"  style="width:30px">
							 Sr. No
						</th> 
						<th align="left" style="width:100px">
							 Airwaybill
						</th>  
						<th align="left">
							 Ref. No.
						</th> 
						<th align="left" style="width:100px">
							 Attention
						</th> 
						<th align="left" style="width:100px">
							 City / State
						</th>
						<th align="left">
							 Contents
						</th>
						<th align="left">
							 Weight
						</th>
						<th align="left">
							 Product Type
						</th>
						<th align="center" width="100">
							 Airwaybill Number
						</th>
					</tr>
					<?php foreach($results as $key=>$rslt){ ?>
					<?php 
						$_order = Mage::getModel('sales/order')->load($rslt['order_id']);
						$_shippingAddress = $_order->getShippingAddress();
						$first_name = $_shippingAddress->getFirstname() ;
						$last_name  = $_shippingAddress->getLastname() ; 
						$street		= $_shippingAddress->getStreetFull() ;
						$region 	= $_shippingAddress->getRegion() ;
						$city		= $_shippingAddress->getCity() ;
						$post_code	= $_shippingAddress->getPostcode();
						$telephone	= $_shippingAddress->getTelephone() ;
						$country_id	= $_shippingAddress->getCountry_id()  ; 
						 
					?>
					<tr>
						<td align="left">
							<?php echo ($key + 1) ?>
						</td> 
						<td align="left">
							<?php echo $rslt['awb'] ?>
						</td>  
						<td align="left">
							 <?php echo $_order->getIncrement_id() ?>
						</td> 
						<td align="left">
							<?php echo $rslt['customer_name'] ?>
						</td> 
						<td align="left">
							 <?php echo $city.'/<br/>'.$region ; ?>
						</td>
						<td align="left">
							 Precious <br/> Jewellery
						</td>
						<td align="left">
							 500 gms
						</td>
						<td align="left">
							 Product
						</td>
						<td align="left">
							<?php $file = base_url() .'uploads/barcode/'. $rslt['awb'].'.jpg' ;?>
									
							<img src="<?php echo $file ; ?>" alt="<?php echo $rslt['awb'] ; ?>"/>
							 
						</td>
					</tr>
					<?php } ?>
					
					
				</table>  
			</td>
		</tr>  
	</table>
	<div class="signature">
		 <br/><br/><br/><br/>Name:............................................................................... Phone:......................................<br/><br/>
		 signature:....................................... Date:..........................................................
	</div> 
</div>
<br/>

<a title="Go Back to Orders" style="float: right;" href="<?php echo base_url(); ?>index.php/bluedartshippingprint/">Go Back to Orders</a>

<a title="Export Soft Data" style="float: right;margin-right: 30px;" href="<?php echo base_url(); ?>index.php/bluedartshippingprint/exportsoftdata?batch_id=<?php echo $batch_id ;?>">Export Soft Data</a>

<a title="Email Soft Data" style="float: right;margin-right: 30px;" href="<?php echo base_url(); ?>index.php/bluedartshippingprint/emailexportsoftdata?batch_id=<?php echo $batch_id ;?>">Email Soft Data</a>
 
<input name="b_print" style="float: right;margin-right: 30px;" type="button" class="ipt"  onClick="PrintDivOnly();" style="float:right;" value="Print This Now">


<br/>